### ISSUE TITLE
When a non-speech trsnslation is invoked in two windows the app makes both windows to be  set to the same translation... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#322]
1) Top window is ESV

2) Bottom window is WLC or HISB (some translation that the speech can not speak)

3) tap on the bottom window and from the menu try to invoked speech. You get a message that the language is not supported, so far everything is good.

4) tap on the top window and invoked speech from the menu bar.
Both windows are now set to ESV

**Comment by tuomas2** [comment]
Fixed in 4a8771cdbd1befb7691f34fae49845c7ed0c27a7

**Comment by tuomas2** [comment]
Will be fixed in 304

**Comment by bvahedy** [comment]
Tuomas, this bug is still happening, can you see if you can duplicate it.

I'll reopen the ticket, until we figure out what's going on.

**Comment by tuomas2** [comment]
Will be fixed (again) in 305

**Comment by bvahedy** [comment]
This is fixed now, thx!
