### ISSUE TITLE
Backup Not Working

### ISSUE THREAD

**Issue by jessemclaren** [AndBible/and-bible#335]
If using 3.1.302 on an ALS UL-40 (arm7, Nougat 7.1, stock) with app in external memory (ie SD card) the backup/restore will not function {'an error has occured' toast is all I get}.  If however, I transfer the app to internal memory the functions work properly.  This is an old Nougat issue, of course, but thought I'd post this in case anyone else gets flustered in thinking the app won't work properly.  Thanks, all.

**Comment by tuomas2** [comment]
Will be fixed by #148

**Comment by tuomas2** [comment]
And thank you @jessemclaren for a good bug report :)

**Comment by tuomas2** [comment]
New "Backup to ..." feature (#148) will allow saving backup to custom location. Fixed in build 307.

**Comment by christiaan** [comment]
Since this is closed does that mean it is released? I have the latest version from the play store and still experience this issue.

Thanks to this bug report by moving the app to internal storage I could save the backup.

I am using the feature of Android 7.1 that adopts the sd card as semi internal storage.

**Comment by timbze** [comment]
@christiaan The stable version in Play Store is the one you have, but this fix has only been released in the beta channel so far (v3.1.307). I don't know yet when it will be released to stable. You can go into play store in the And-Bible page and click join beta and you will be able to download the latest beta and have this fix.
