### ISSUE TITLE
Window gets reloaded even though it's same content

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#449]
**Screen video**
https://photos.app.goo.gl/kpHfaZ7gt27Wsx7A6

**To Reproduce**
1. Open Bible window in top window
2. Open Matthew Henry commentary in bottom window
3. Have sync on for windows and Go to Romans 4:9
4. Matthew Henry commentary has the same content for v9 to v17
5. Scroll in the commentary
6. Scroll in Bible to v10, commentary gets reloaded and jumps back to top

**Expected behavior**
As long as commentary content is the same, it should not get reloaded.

Maybe this is just a feature request, and not a bug. I think And Bible has always been behaving like this.

**Comment by tuomas2** [comment]
Probably fixed in 319.3

**Comment by timbze** [comment]
Issue is still there. I think the code probably doesn't check to see if it's the same content. I'm guessing it only checks if the verse number changed.

**Comment by tuomas2** [comment]
Issue reported on version 319.2.

**Comment by tuomas2** [comment]
Sorry for not reading the description...

Investigated this a little.

And Bible queries module with `SwordContentFacade#readHtmlTextStandardJSwordMethod`. 

I didn't go very deep into jsword code, but quickly I can't find any way to obtain verserange in which currently shown passage belongs to. Thus I'm not sure if this can be fixed nicely.

**Comment by bvahedy** [comment]
I tried this with TSK and it seems to function correctly in beta build 319.3
Like you mentioned this may be the way it's supposed to work.
